name = "petcare"
compatibility_date = "2024-01-01"

[pages]
# Build configuration for Next.js
pages_build_output_dir = ".next"

[[pages.build_config]]
command = "npm run build"
cwd = "."
watch_dir = "app"

[env.production]
vars = { NODE_ENV = "production" }
